# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Newspaper.io 
email: contact@newspaper.io
description: > # this means to ignore newlines until "baseurl:"
  Newspaper delivers the best content for the topics that interest you straight onto Slack.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: newspaperio 
github_username: newspaperhq 

  # Build settings
markdown: kramdown

permalink: pretty

gems:
  - jekyll-coffeescript

navigation:
  - text: Home
    url: /
  - text: Getting Started
    url: /slack/getting_started/
  - text: FAQ
    url: /slack/faq/


